### ISSUE TITLE
 400 Bad Request

### ISSUE THREAD

**Issue by logictom** [michalrus/gitlab-ci-bot#1]
I have just pulled the repo and created a config but I am getting a 400 error at http://192.168.0.99:8089

Set up a user in gitlab, merge-bot, with master access to test repo
Config:

```
my_handle => 'merge-bot',
required_lgtms => 2,
private_token => 'tokenhere',
gitlab_url => 'http://192.168.0.99:88',
```

GitLab v8.4.4 CE
GitLab API v3
Running on local server @ 192.168.0.99:88 (Ubuntu 14.04)

Not sure where to head from here

**Comment by katzien** [comment]
My rough guess based on looking at the source code is that your webhook to the webserver is not a POST, which is why you're getting a 400. Did you configure the webhook to be sent to your merge bot in gitlab? Or how did you set this up?

**Comment by michalrus** [comment]
@logictom, exactly that, @katzien is right. The script just allows for one type of a request—the one sent by GitLabs hook dispatcher.
